import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[2];O=R/'assets/art/environments/master_office_3d/source/env_block00_story_rooms/v001';O.mkdir(parents=True,exist_ok=True);(O.parent/'.gdignore').touch()
layout=R/'source/art/blender/master_office_layout/source/block_00_master_office_layout_v002.layout.json'
data=json.loads(layout.read_text(encoding='utf8'));office=R/'assets/art/environments/master_office_3d/source/env_father_office/v002/env_father_office_source_v002.blend'
defs=[('sculpture_foundry','铸造者纪念雕塑','sculpture','facilities'),('sculpture_turbine','涡轮与钢翼雕塑','sculpture','facilities'),('sculpture_pylon','工业之峰雕塑','sculpture','facilities'),('debris_slab','破碎楼板残片','debris','decoration'),('debris_cluster','边缘混凝土废墟','debris','decoration'),('cable_floor','地面断裂电缆束','cable','support'),('cable_hanging','垂落断线','cable','support'),('portal_damage','拆门残留断框','portal_damage','architecture'),('constructivist_mural','工业时代构成主义壁画','mural','decoration')]
components=[dict(slug=s,name_zh=n,component_family=f,category=c,component_id='ENV-BLOCK00-'+s.upper().replace('_','-'),scope='room_type_local',serves_room_types=['STORY_MEETING','STORY_CORRIDOR','STORY_LOBBY'] if f in ['debris','cable'] else ['STORY_MEETING' if f=='sculpture' else 'STORY_LOBBY'],variant_axis='sculpture_theme' if f=='sculpture' else 'structure_state',variant_value=s,variant_reason='用户要求的三种棱角工业雕塑或不同废墟形态',front_axis='+Y',allowed_rotations_y_deg=[0,90,180,270]) for s,n,f,c in defs]
plan=dict(asset_id='ENV-BATTLE-BLOCK00-STORY-ROOMS-SOURCE',block_id='master_office',floor_range=[98,98],design_scope='scene_art_source_only',whitebox_source=str(layout.relative_to(R)),whitebox_sha256=hashlib.sha256(layout.read_bytes()).hexdigest(),rooms=data['rooms'],source_office=str(office.relative_to(R)),source_office_sha256=hashlib.sha256(office.read_bytes()).hexdigest(),components=components,component_plan_frozen=True,unique_new_components=9,linked_components=24,total_unique_components=33,sculpture_triangle_budget_each=1500,meeting_clear_lane={'x':[-25,15],'y':[-.5,5.5],'z':[.30,4.0]},door_removal={'rooms':['corridor','lobby'],'wall_x':20,'opening_y':[0,5],'remove':['door_wall','door_leaf'],'clear_width_m':5,'source_only':True},asset_ledger='assets/registry/ledger_index.json::scenes::资产主表',scene_design_docs=['docs/v0.1/05.1_关卡区块设计.md','docs/v0.1/05.2_关卡版图白盒与生成规范.md','src/world3d/Block00MasterOfficeLayout3D.gd'],notes=['用户要求会议室中间无阻挡，上下两侧按南北两侧解释，各排6尊大型雕塑。','第三间为corridor，第四间为lobby；背面墙取门厅北墙Y=10。','只修改本次Blender源中的第三/第四房连接，不覆盖旧运行时JSON或Godot场景。','现有办公室以Library Link引用，自持网格0。'])
(O/'component_plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf8')
print('PLAN_FROZEN',len(components))
