import json,hashlib,struct
from pathlib import Path
P=Path('I:/工作项目/shellstrom2/ShellStorm2'); O=P/'outputs/base99_radio_v005'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
m=json.loads((O/'asset_manifest.json').read_text(encoding='utf-8'))
prefab=P/'assets/art/props/base_world_3d/runtime/base99_radio/prp_base99_radio_root_top3d.tscn'
m['hashes_sha256']['prefab']=sha(prefab); m['faces']=600; m['triangles']=1200; m['hashes_sha256']['source']=sha(P/'assets/art/props/base_world_3d/source/base99_radio/prp_base99_radio_source_v005.blend'); m['hashes_sha256']['optimized']=sha(P/'assets/art/props/base_world_3d/source/base99_radio/export/v005/prp_base99_radio_optimized_v005.blend'); m['hashes_sha256']['glb']=sha(P/'assets/art/props/base_world_3d/components/base99_radio/prp_base99_radio_visual_top3d.glb'); (O/'asset_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
val_s=json.loads((O/'validation/validate_source_current.json').read_text(encoding='utf-8')); val_o=json.loads((O/'validation/validate_optimized_current.json').read_text(encoding='utf-8')); pix=json.loads((O/'status_light_pixel_metrics.json').read_text(encoding='utf-8'))
accept={'asset_id':'PRP-BASE99-RADIO-3D','version':'v005','passed':False,'status':'待账本事务与正式运行时回归完成；几何/UV/渲染证据已更新，旧运行时验证日志不适用于本次600面导出','geometry':{'faces':600,'triangles':1200,'face_budget_lt_800':True,'bounds_m':[0.82799995,0.45600003,0.82200003],'root_scale':[1,1,1],'status_light':m['status_light'],'source_hash':m['hashes_sha256']['source'],'optimized_hash':m['hashes_sha256']['optimized'],'glb_hash':m['hashes_sha256']['glb'],'prefab_hash':m['hashes_sha256']['prefab']},'materials_uv':{'source_passed':val_s['passed'],'optimized_passed':val_o['passed'],'source_polygon_count':val_s['polygon_count'],'optimized_polygon_count':val_o['polygon_count'],'palette':m['palette']},'visual_evidence':{'resolution':[1280,720],'mask_metrics':'status_light_pixel_metrics.json','pixel_metrics':'pixel_metrics.json','before_v004_closeup':'before_v004_closeup_off.png','v005_closeup_off':'v005_closeup_off.png','v005_closeup_green':'v005_closeup_green.png','attic_off':'attic_off.png','attic_a':'attic_a.png','attic_b':'attic_b.png','mask_area_ratio_before':1704/(1280*720),'mask_area_ratio_after':9518/(1280*720),'mask_area_increase':9518/1704,'note':'本轮 Blender 近景红绿材质统计脚本仅对既有文件名运行；全阁楼 PNG 为既有正常玩家 Vulkan 证据，需待正式GLB重导后重拍才能宣称新运行时像素通过。'},'runtime':{'prefab_version':'v005','reimport_log':'reimport_repair.log','import_script':'res://tools/asset_pipeline/scene_facility_shared_palette_post_import.gd','interaction':'未用旧 verify_window_final2.log 作为本轮通过证据','music_logic_untouched':True},'gates':{'source_uv':val_s['passed'],'optimized_uv':val_o['passed'],'structure':'see structure_final.log','split':'see split_final.log','full_props':'既有红项，待重跑后归档','runtime_interaction':'pending','ledger_sync':'pending'}}
(O/'final_acceptance.json').write_text(json.dumps(accept,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('RADIO_V005_CURRENT_EVIDENCE_WRITTEN')
