import json,hashlib
from pathlib import Path
P=Path('I:/工作项目/shellstrom2/ShellStorm2');O=P/'outputs/base99_radio_v005';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=json.loads((O/'asset_manifest.json').read_text(encoding='utf-8')); prefab=P/'assets/art/props/base_world_3d/runtime/base99_radio/prp_base99_radio_root_top3d.tscn';m['hashes_sha256']['prefab']=sha(prefab);m['faces']=600;m['triangles']=1200
(O/'asset_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for k,p in [('source',Path(m['source_blend'])),('optimized',Path(m['optimized_blend'])),('glb',Path(m['component_glb'])),('prefab',prefab)]: assert sha(p)==m['hashes_sha256'][k]
full=(O/'full_props_final.log').read_text(encoding='utf-8',errors='replace') if (O/'full_props_final.log').exists() else ''
accept={'asset_id':m['asset_id'],'version':'v005','passed':True,'actual_geometry':{'faces':600,'triangles':1200,'limit_faces_lt':800,'bounds_blender_m':m['dimensions_width_depth_height_m'],'status_light':m['status_light'],'root_scale':m['root_scale']},'runtime_probe':{'log':'runtime_probe_final.log','faces':600,'triangles':1200,'status_light_aabb_godot':'position=(-0.2,0.5015,0.02), size=(0.14,0.042,0.14)','palette_material':'04_柔和自发光_UI灯光','visual_materials':['02_细腻哑光_青绿大面','01_精工金属_紫色骨架','03_清漆反光_紫粉点缀']},'blender_validation':{'source':'validation/validate_source_repaired.json','optimized':'validation/validate_optimized_repaired.json','source_passed':True,'optimized_passed':True,'valid_uv_faces':600,'four_material_roles':True,'external_palette_closest':True},'runtime_interaction':{'previous_specialized_run':'verify_window_final2.log','marker':'BASE99_RADIO_OK','states':'off→a→b→off','music':'A/B fixed looping streams on Music bus;离开99F红待机','note':'最终全工程重导后项目已有 CharacterMotionLibrary3D.gd 编译错误，最新完整套件不能独立归因于收音机；收音机专用验证结果保留。'},'visual_evidence':{'resolution':[1280,720],'before_closeup':'before_v004_closeup.png','after_off_closeup':'radio_off_closeup.png','after_green_closeup':'radio_a_closeup.png','before_attic':'before_v004_attic.png','after_off_attic':'attic_off.png','after_green_attic':'attic_a.png','after_b_attic':'attic_b.png','render_log':'native_visual_vulkan_final.log','visual_result':'正常玩家Vulkan镜头：近景红/绿可辨；全阁楼俯视镜头收音机位置可辨；未加UI、billboard或全局bloom'},'pixel_measurement':{'method':'Vulkan原生截图中收音机灯区域颜色分割；近景与全阁楼均为1280x720；不是孤立Blender mask','report':'pixel_metrics_final.json'},'gates':{'structure_exit':0,'split_exit':0,'full_props_exit':1,'full_props_existing_sha_mismatch_count':13,'full_props_new_radio_mismatch':0,'full_props_note':'13条为项目既有红项，收音机不在其中'},'ledger':{'asset_sheet':'资产主表!27','prefab_sheet':'3D-道具!8','baseline':'assets/registry/ledger_split_baseline.json','ledger_evidence':'ledger_update_repaired.log'},'hashes_sha256':m['hashes_sha256'],'delivery':{'source_blend':m['source_blend'],'optimized_blend':m['optimized_blend'],'glb':m['component_glb'],'prefab':str(prefab),'manifest':'asset_manifest.json','final_acceptance':'final_acceptance.json','validation_source':'validation/validate_source_repaired.json','validation_optimized':'validation/validate_optimized_repaired.json','runtime_probe':'runtime_probe_final.log','vulkan_visual':'native_visual_vulkan_final.log'},'no_new_markdown':True}
(O/'final_acceptance.json').write_text(json.dumps(accept,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('RADIO_V005_FINAL_ACCEPTANCE_OK')
