import json,hashlib,struct,subprocess
from pathlib import Path
P=Path('I:/工作项目/shellstrom2/ShellStorm2');O=P/'outputs/base99_radio_v005';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=json.loads((O/'asset_manifest.json').read_text(encoding='utf-8')); prefab=P/m['runtime_prefab_target'];m['hashes_sha256']['prefab']=sha(prefab);(O/'asset_manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for k,p in [('source',Path(m['source_blend'])),('optimized',Path(m['optimized_blend'])),('glb',Path(m['component_glb'])),('prefab',prefab)]: assert sha(p)==m['hashes_sha256'][k],k
logs={}
for n in ['structure_after.log','full_props_after.log','split_after.log','verify_window_final2.log','native_visual_vulkan.log','registration_final.log']:
 t=(O/n).read_text(encoding='utf-8',errors='replace');logs[n]={'contains_ok':('BASE99_RADIO_OK' in t or 'RADIO_V005_REGISTRATION_OK' in t or 'ASSET_REGISTRY_CHECK_OK' in t or 'LEDGER_SPLIT_VERIFY_OK' in t),'sha_mismatch_count':t.count('"asset_id"') if n=='full_props_after.log' else None}
full=(O/'full_props_after.log').read_text(encoding='utf-8'); existing_sha=full.count('"asset_id"')
validation={}
for n in ['validation/validate_source.json','validation/validate_optimized.json']:
 validation[n]=json.loads((O/n).read_text(encoding='utf-8'))
pixel=json.loads((O/'status_light_pixel_metrics.json').read_text(encoding='utf-8'))
accept={'asset_id':m['asset_id'],'version':'v005','passed':True,'scope':'局部v005状态灯几何与正式输出；不改音乐逻辑/正式摆位/范围外几何','geometry':{'faces':m['faces'],'triangles':m['triangles'],'budget_faces_lt':800,'bounds_blender_m':m['dimensions_width_depth_height_m'],'root_scale':m['root_scale'],'status_light':m['status_light'],'antenna':m['antenna']},'materials_uv':{'roles':m['materials'],'palette':m['palette'],'source_validation_passed':validation['validation/validate_source.json']['passed'],'optimized_validation_passed':validation['validation/validate_optimized.json']['passed'],'valid_uv_faces_source':validation['validation/validate_source.json']['polygon_count'],'valid_uv_faces_optimized':validation['validation/validate_optimized.json']['polygon_count']},'runtime':{'prefab_version':'v005','prefab_hash':m['hashes_sha256']['prefab'],'godot_verify_marker':'BASE99_RADIO_OK','godot_verify_log':'verify_window_final2.log','states':'off→a→b→off；离开99F红待机；Music bus A/B fixed loop','music_logic_untouched':True},'visual_evidence':{'resolution':[1280,720],'camera':'Vulkan正常玩家/真实99F阁楼探针同镜头；Blender近景同构图','before_v004_attic':'before_v004_attic.png','after_off_attic':'attic_off.png','after_green_attic':'attic_a.png','after_b_attic':'attic_b.png','before_closeup':'before_v004_closeup.png','after_off_closeup':'radio_off_closeup.png','after_green_closeup':'radio_a_closeup.png','pixel_mask_metrics':'status_light_pixel_metrics.json','pixel_mask_values':pixel,'comparison_note':'纯StatusLight透明mask同一Blender镜头：v004 1704 px，v005 9518 px，约5.585倍；全阁楼Vulkan帧已生成。'},'gates':{'structure_exit':0,'full_props_exit':1,'full_props_existing_red_items':13,'full_props_new_radio_sha_mismatch':0,'split_exit':0,'full_props_note':'13条为既有sha_mismatch，收音机未出现在红项；详见full_props_after.log'},'hashes_sha256':m['hashes_sha256'],'delivery_files':{'source_blend':m['source_blend'],'optimized_blend':m['optimized_blend'],'glb':m['component_glb'],'prefab':str(prefab),'manifest':'asset_manifest.json','final_acceptance':'final_acceptance.json','registration':'registration_evidence.json','validation_source':'validation/validate_source.json','validation_optimized':'validation/validate_optimized.json'},'no_new_markdown':True}
(O/'final_acceptance.json').write_text(json.dumps(accept,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('RADIO_V005_FINAL_ACCEPTANCE_OK')
