from pathlib import Path
src = Path(r'I:/工作项目/shellstrom2/ShellStorm2/_scratch/security_zombie/author_reference_walk_mcp.py')
dst = Path(r'I:/工作项目/shellstrom2/ShellStorm2/_scratch/security_zombie/author_reference_walk_v002_mcp.py')
text = src.read_text(encoding='utf-8')
repls = [
("P = Path('I:/工作项目/shellstrom2/outputs/zombie_walk_reference')", "P = Path('I:/工作项目/shellstrom2/outputs/zombie_walk_reference_v002')\nP.mkdir(parents=True, exist_ok=True)"),
("s.name='01_Walk_InPlace'; s.render.fps=24; s.frame_start=1; s.frame_end=120", "s.name='02_Walk_InPlace_ReferenceFront'; s.render.fps=24; s.frame_start=1; s.frame_end=120"),
("act=bpy.data.actions.new('Zombie_Walk_Reference_24fps_v001')", "act=bpy.data.actions.new('Zombie_Walk_Reference_24fps_v002')"),
("def track(t,keys):\n for (ta,va),(tb,vb) in zip(keys,keys[1:]):\n  if t<=tb:\n   u=max(0,min(1,(t-ta)/(tb-ta)));return va+(vb-va)*u\n return keys[-1][1]", "def track(t,keys):\n for (ta,va),(tb,vb) in zip(keys,keys[1:]):\n  if t<=tb:\n   u=max(0,min(1,(t-ta)/(tb-ta)));u=u*u*(3-2*u);return va+(vb-va)*u\n return keys[-1][1]"),
(" # Reference front section: alternating shoe-forward peaks approximately every 12 frames.\n t=((f-1)/24+.10)%1;ph=2*math.pi*t\n Q={n:Quaternion() for n in rest};hip=heads['Hip'].copy();hip.z-=.039+.007*math.cos(2*ph);hip.x+=.013*math.sin(ph)\n Q['Hip']=ry(1.2*math.sin(ph))@rz(1.6*math.sin(ph));Q['Waist']=rx(-3)@ry(1.8*math.sin(ph));Q['Spine01']=rx(-4)@ry(2.4*math.sin(ph));Q['Spine02']=rx(-5)@ry(3*math.sin(ph))@rz(-2.3*math.sin(ph))\n Q['Neck']=rx(-2)@ry(1.5*math.sin(ph));Q['Head']=rx(-1+.8*math.sin(ph-.3))@ry(1.4*math.sin(ph-.25));Q['HeadTop_End']=Q['Head']", " # V002 follows the front-half reference timing: contact, weight transfer, toe-off,\n # passing, forward swing, then the next contact. The old version used a near-sine\n # path and only 0.15 m of fore/aft travel, which made the feet look pinned.\n t=((f-1)/24)%1;ph=2*math.pi*t\n Q={n:Quaternion() for n in rest};hip=heads['Hip'].copy();hip.z-=.035+.010*(.5+.5*math.cos(2*ph));hip.x+=.018*math.sin(ph)\n Q['Hip']=ry(1.8*math.sin(ph))@rz(2.4*math.sin(ph));Q['Waist']=rx(-4)@ry(2.4*math.sin(ph));Q['Spine01']=rx(-5)@ry(3.2*math.sin(ph));Q['Spine02']=rx(-6)@ry(4.0*math.sin(ph))@rz(-3.0*math.sin(ph))\n Q['Neck']=rx(-2.5)@ry(1.8*math.sin(ph));Q['Head']=rx(-1.2+.9*math.sin(ph-.3))@ry(1.8*math.sin(ph-.25));Q['HeadTop_End']=Q['Head']"),
("  u=(t+off)%1; swing=math.sin(2*math.pi*u)\n  Q[side+'_Clavicle']=Q['Spine02']\n  Q[side+'_Upperarm']=Q['Spine02']@aim(side+'_Upperarm',(sgn*.60,.72+.14*swing,-.27))\n  Q[side+'_Forearm']=Q['Spine02']@aim(side+'_Forearm',(sgn*.27,.91+.16*swing,-.23))\n  Q[side+'_Hand']=Q['Spine02']@aim(side+'_Hand',(sgn*.20,.94+.12*swing,-.35))", "  u=(t+off)%1; swing=math.sin(2*math.pi*u)\n  Q[side+'_Clavicle']=Q['Spine02']\n  Q[side+'_Upperarm']=Q['Spine02']@aim(side+'_Upperarm',(sgn*.60,.72+.18*swing,-.27))\n  Q[side+'_Forearm']=Q['Spine02']@aim(side+'_Forearm',(sgn*.27,.91+.20*swing,-.23))\n  Q[side+'_Hand']=Q['Spine02']@aim(side+'_Hand',(sgn*.20,.94+.15*swing,-.35))"),
("  u=(t+off)%1; stance=.57\n  target=heads[side+'_Foot'].copy()\n  if u<stance:\n   v=u/stance;target.y+=.075-.15*v\n   pitch[side]=track(v,[(0,-9),(.16,0),(.80,0),(1,10)])\n   desired_low[side]=.001;states[side]='stance'\n  else:\n   v=(u-stance)/(1-stance);target.y+=-.075+.15*(v*v*(3-2*v))\n   desired_low[side]=.001+.039*math.sin(math.pi*v)**1.4\n   target.z+=desired_low[side]-.001\n   pitch[side]=track(v,[(0,10),(.28,16),(.65,-12),(1,-9)]);states[side]='swing'", "  u=(t+off)%1\n  target=heads[side+'_Foot'].copy()\n  # Five visible beats in the 24-frame cycle.  The foot travels 0.28 m\n  # front-to-back during support and returns forward during swing.\n  # x offsets create the alternating lateral clearance visible from the front.\n  target.x += sgn * track(u,[(0.00,.010),(.18,.018),(.40,.025),(.52,.050),(.70,.045),(.88,.018),(1.00,.010)])\n  if u < .42:\n   v=u/.42\n   target.y += track(v,[(0.0,.145),(.18,.105),(.65,.015),(1.0,-.090)])\n   desired_low[side]=.001 + .002*math.sin(math.pi*v)\n   pitch[side]=track(v,[(0,-12),(.18,-5),(.70,4),(1,12)])\n   states[side]='stance'\n  else:\n   v=(u-.42)/.58\n   target.y += track(v,[(0,-.090),(.14,-.125),(.34,.010),(.62,.135),(.84,.165),(1,.145)])\n   desired_low[side]=.001 + .067*math.sin(math.pi*v)**1.25\n   pitch[side]=track(v,[(0,12),(.20,18),(.48,-16),(.78,-7),(1,-12)])\n   states[side]='swing'"),
("act['cycle_frames']=24;act['duration_seconds']=5.0", "act['cycle_frames']=24;act['duration_seconds']=5.0;act['iteration']='v002: front-reference timing, explicit contact/passing/swing path, increased stride and lateral clearance'"),
("report={'status':'pending_visual_review'", "report={'status':'pending_visual_review','iteration':'v002_front_reference_stride'"),
("str(P/'zombie_reference_walk_v001.blend')", "str(P/'zombie_reference_walk_v002.blend')"),
("'pose_%03d.png'%f", "'pose_v002_%03d.png'%f"),
]
for old,new in repls:
    if old not in text:
        raise SystemExit('missing replacement: ' + old[:80])
    text = text.replace(old,new,1)
dst.write_text(text, encoding='utf-8')
print(dst)
